{
 "title": "LFU Cache Monitor",
 "time": { "from": "now-2m", "to": "now" },
 "panels": [
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(request_duration_seconds_sum[1m])/rate(request_duration_seconds_count[1m])\n",
     "legendFormat": "{{symbol}},{{cache}}"
    }
   ]
  },
  {
   "title": "Cache Config ",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "options": {
    "content": "<p>\n  Cache Eviction: LFU;<br/>\n\t\t\tCapacity: 10;<br/>\n\t\t\tBots: 20;<br/>\n\t\t\tEach bot hitting 50 requests\n</p>"
   }
  },
  {
   "title": "Cache miss total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cache_misses_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache Ratio",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cache_hit_ratio\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Cache hits total",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cache_hits_total\n", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Top Requests",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "top_symbols_requests\n", "legendFormat": "{{symbol}}" }
   ]
  }
 ]
}